apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    categories: "OpenShift Optional, Security"
    description: |
      An operator which runs OpenSCAP and allows you to check your cluster for
      security vulnerabilities and to keep your it compliant with the
      security benchmark you need.
    containerImage: quay.io/compliance-operator/compliance-operator:latest
    createdAt: 2020-01-28T08:00:00Z
    support: OpenShift Security & Compliance
    repository: https://github.com/openshift/compliance-operator
    certified: "false"
    alm-examples: |-
      [
        {
          "apiVersion": "complianceoperator.compliance.openshift.io/v1alpha1",
          "kind": "ComplianceRemediation",
          "metadata": {
            "labels": {
              "complianceoperator.openshift.io/scan": "example-scan",
              "complianceoperator.openshift.io/suite": "example-suite",
              "machineconfiguration.openshift.io/role": "worker"
            },
            "name": "example-remediation-worker-no-direct-root-login",
            "namespace": "openshift-compliance"
          },
          "spec": {
            "apply": false,
            "machineConfigContents": {
              "apiVersion": "machineconfiguration.openshift.io/v1",
              "kind": "MachineConfig",
              "spec": {
                "config": {
                  "ignition": {
                    "version": "2.2.0"
                  },
                  "storage": {
                    "files": [
                      {
                        "contents": {
                          "source": "data:,"
                        },
                        "filesystem": "root",
                        "mode": 384,
                        "path": "/etc/securetty"
                      }
                    ]
                  }
                },
                "fips": false,
                "kernelArguments": [
                  ""
                ],
                "osImageURL": ""
              }
            },
            "type": "MachineConfig"
          }
        },
        {
          "apiVersion": "complianceoperator.compliance.openshift.io/v1alpha1",
          "kind": "ComplianceScan",
          "metadata": {
            "name": "example-compliancescan"
          },
          "spec": {
            "content": "ssg-ocp4-ds.xml",
            "profile": "xccdf_org.ssgproject.content_profile_coreos-ncp"
          }
        },
        {
          "apiVersion": "complianceoperator.compliance.openshift.io/v1alpha1",
          "kind": "ComplianceSuite",
          "metadata": {
            "name": "example-compliancesuite"
          },
          "spec": {
            "autoApplyRemediations": true,
            "scans": [
              {
                "content": "ssg-ocp4-ds.xml",
                "contentImage": "quay.io/jhrozek/ocp4-openscap-content:remediation_demo",
                "name": "workers-scan",
                "nodeSelector": {
                  "node-role.kubernetes.io/worker": ""
                },
                "profile": "xccdf_org.ssgproject.content_profile_coreos-ncp"
              },
              {
                "content": "ssg-ocp4-ds.xml",
                "contentImage": "quay.io/jhrozek/ocp4-openscap-content:remediation_demo",
                "name": "masters-scan",
                "nodeSelector": {
                  "node-role.kubernetes.io/master": ""
                },
                "profile": "xccdf_org.ssgproject.content_profile_coreos-ncp"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
  name: compliance-operator.v0.1.0
  namespace: openshift-compliance
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ComplianceRemediation is the Schema for the complianceremediations
        API
      kind: ComplianceRemediation
      name: complianceremediations.complianceoperator.compliance.openshift.io
      version: v1alpha1
    - description: ComplianceScan is the Schema for the compliancescans API
      kind: ComplianceScan
      name: compliancescans.complianceoperator.compliance.openshift.io
      version: v1alpha1
    - description: ComplianceSuite is the Schema for the compliancesuites API
      kind: ComplianceSuite
      name: compliancesuites.complianceoperator.compliance.openshift.io
      version: v1alpha1
  displayName: Compliance Operator
  description: |
    An operator which runs OpenSCAP and allows you to check your cluster for
    security vulnerabilities and to keep your it compliant with the
    security benchmark you need.
  keywords: ['security', 'compliance', 'openscap', 'audit']
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - list
          - watch
        - apiGroups:
          - machineconfiguration.openshift.io
          resources:
          - machineconfigs
          verbs:
          - list
          - get
          - patch
          - create
          - watch
          - update
          - delete
        serviceAccountName: compliance-operator
      deployments:
      - name: compliance-operator
        spec:
          replicas: 3
          selector:
            matchLabels:
              name: compliance-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: compliance-operator
            spec:
              containers:
              - command:
                - compliance-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: compliance-operator
                - name: OPENSCAP_IMAGE
                  value: quay.io/jhrozek/openscap-ocp:remediations_demo
                image: quay.io/jhrozek/compliance-operator
                imagePullPolicy: Always
                name: compliance-operator
                resources: {}
              nodeSelector:
                node-role.kubernetes.io/master: ""
              serviceAccountName: compliance-operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
                operator: Exists
              - effect: NoExecute
                key: node.kubernetes.io/unreachable
                operator: Exists
                tolerationSeconds: 120
              - effect: NoExecute
                key: node.kubernetes.io/not-ready
                operator: Exists
                tolerationSeconds: 120
      permissions:
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: scc-priv
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - watch
          - create
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - list
          - watch
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - complianceoperator.compliance.openshift.io
          resources:
          - compliancescans
          verbs:
          - create
          - watch
          - patch
          - get
          - list
        - apiGroups:
          - complianceoperator.compliance.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - compliance-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - services
          - services/finalizers
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - compliance-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        serviceAccountName: compliance-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  maintainers:
  - name: Red Hat Inc.
  provider:
    name: Red Hat, Inc
  links:
  - name: compliance-operator
    url: https://github.com/openshift/compliance-operator
  - name: ComplianceAsCode content
    url: https://github.com/ComplianceAsCode/content
  - name: OpenSCAP
    url: https://www.open-scap.org/
  replaces: compliance-operator.v0.0.0
  version: 0.1.0
