apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compliancescans.complianceoperator.compliance.openshift.io
spec:
  group: complianceoperator.compliance.openshift.io
  names:
    kind: ComplianceScan
    listKind: ComplianceScanList
    plural: compliancescans
    singular: compliancescan
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ComplianceScan is the Schema for the compliancescans API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ComplianceScanSpec defines the desired state of ComplianceScan
          properties:
            content:
              type: string
            contentImage:
              type: string
            nodeSelector:
              additionalProperties:
                type: string
              type: object
            profile:
              type: string
            rule:
              type: string
          type: object
        status:
          description: ComplianceScanStatus defines the observed state of ComplianceScan
          properties:
            errormsg:
              type: string
            phase:
              description: Represents the status of the compliance scan run.
              type: string
            result:
              description: Represents the result of the compliance scan
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
