apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceScan
metadata:
  name: example-compliancescan
spec:
  # Add fields here
  profile: xccdf_org.ssgproject.content_profile_moderate
  content: ssg-rhcos4-ds.xml
