apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: compliancescans.compliance.openshift.io
spec:
  group: compliance.openshift.io
  names:
    kind: ComplianceScan
    listKind: ComplianceScanList
    plural: compliancescans
    singular: compliancescan
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.result
      name: Result
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ComplianceScan represents a scan with a certain configuration
          that will be applied to objects of a certain entity in the host. These could
          be nodes that apply to a certain nodeSelector, or the cluster itself.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: The spec is the configuration for the compliance scan.
            properties:
              content:
                description: Is the path to the file that contains the content (the
                  data stream). Note that the path needs to be relative to the `/`
                  (root) directory, as it is in the ContentImage
                type: string
              contentImage:
                description: Is the image with the content (Data Stream), that will
                  be used to run OpenSCAP.
                type: string
              debug:
                description: Enable debug logging of workloads and OpenSCAP
                type: boolean
              nodeSelector:
                additionalProperties:
                  type: string
                description: By setting this, it's possible to only run the scan on
                  certain nodes in the cluster. Note that when applying remediations
                  generated from the scan, this should match the selector of the MachineConfigPool
                  you want to apply the remediations to.
                type: object
              profile:
                description: Is the profile in the data stream to be used. This is
                  the collection of rules that will be checked for.
                type: string
              rawResultStorageRotation:
                default: 3
                description: Specifies the amount of scans for which the raw results
                  will be stored. Older results will get rotated, and it's the responsibility
                  of administrators to store these results elsewhere before rotation
                  happens. Note that a rotation policy of '0' disables rotation entirely.
                  Defaults to 3.
                type: integer
              rawResultStorageSize:
                default: 1Gi
                description: Specifies the amount of storage to ask for storing the
                  raw results. Note that if re-scans happen, the new results will
                  also need to be stored. Defaults to 1Gi.
                type: string
              rule:
                description: A Rule can be specified if the scan should check only
                  for a specific rule. Note that when leaving this empty, the scan
                  will check for all the rules for a specific profile.
                type: string
              scanType:
                description: The type of Compliance scan.
                type: string
              tailoringConfigMap:
                description: Is a reference to a ConfigMap that contains the tailoring
                  file. It assumes a key called `tailoring.xml` which will have the
                  tailoring contents.
                properties:
                  name:
                    description: Name of the ConfigMap being referenced
                    type: string
                required:
                - name
                type: object
            type: object
          status:
            description: The status will give valuable information on what's going
              on with the scan; and, more importantly, if the scan is successful (compliant)
              or not (non-compliant)
            properties:
              currentIndex:
                description: Specifies the current index of the scan. Given multiple
                  scans, this marks the amount that have been executed.
                format: int64
                type: integer
              errormsg:
                description: If there are issues on the scan, this will be filled
                  up with an error message.
                type: string
              phase:
                description: Is the phase where the scan is at. Normally, one must
                  wait for the scan to reach the phase DONE.
                type: string
              result:
                description: Once the scan reaches the phase DONE, this will contain
                  the result of the scan. Where COMPLIANT means that the scan succeeded;
                  NON-COMPLIANT means that there were rule violations; and ERROR means
                  that the scan couldn't complete due to an issue.
                type: string
              resultsStorage:
                description: Specifies the object that's storing the raw results for
                  the scan.
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  kind:
                    description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                  namespace:
                    description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
