apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compliancecheckresults.compliance.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status
    name: Status
    type: string
  group: compliance.openshift.io
  names:
    kind: ComplianceCheckResult
    listKind: ComplianceCheckResultList
    plural: compliancecheckresults
    singular: compliancecheckresult
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: ComplianceCheckResult represent a result of a single compliance
        "test"
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        description:
          description: A human-readable check description, what and why it does
          type: string
        id:
          description: A unique identifier of a check
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        result:
          description: The result of a check
          type: string
      required:
      - id
      - result
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
