apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-compliance
  name: compliance-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods        # Pods are used to run the compliance container
  verbs:
  - watch       # The operator needs to watch for the container status
  - create      # The operator needs to spawn the containers
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps  # The log collecting sidecar uses configmaps to store results
  verbs:
  - create      # The sidecar must create the configmap to store results in
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get         # Otherwise the operator errors out when creating initializing metrics
- apiGroups:
  - complianceoperator.compliance.openshift.io
  resources:
  - compliancescans   # The operator's custom CRD
  verbs:
  - watch       # The operator must be able to watch the CR for changes
  - patch       # The operator changes the CR status to run a state machine
  - get         # The operator must be able to read the CR
  - list        # The operator must be able to read the CR
- apiGroups:
  - complianceoperator.compliance.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - compliance-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-priv
  namespace: openshift-compliance
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
