apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openscap
  name: openscap-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - openscap.compliance.openshift.io
  resources:
  - openscaps
  verbs:
  - watch
  - patch
  - get
