apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resultscollector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-aggregator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rerunner