name: Docker Image CI

on:
  push:
    branches: [ new-feature ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.ci --tag compliance-operator:$(date +%s)
